# Options: HCFactions, Factions
#
# Known Supported list:
# Factions:
#  - https://www.spigotmc.org/resources/factions.1900/
#  -
#
# HCFactions:
#  - https://github.com/drtshock/HCFactions (And any fork of it.)
#  -
#   Will it work?
#    If the path: com.massivecraft.factions.FPlayers and com.massivecraft.factions.Faction
#    exists inside the plugin then this will be supported and if you could send me a link to the download page
#    so it can be included in the supported file to my spigot profile. https://www.spigotmc.org/members/eqx.24492/
#
#
#
factions_type: 'add_faction_here'